{{- if .Values.messageQueue.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "msa.fullname" . }}-message-queue
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "msa.fullname" . }}-message-queue
  ports:
    - name: http
      port: {{ .Values.messageQueue.port }}
      targetPort: {{ .Values.messageQueue.port }}
      protocol: TCP
    - name: tcp
      port: {{ .Values.messageQueue.tcpPort }}
      targetPort: {{ .Values.messageQueue.tcpPort }}
      protocol: TCP
{{- end }}
