{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "msa.fullname" . }}-metrics
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "msa.fullname" . }}-metrics
  ports:
    - port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
      protocol: TCP
{{- end }}
