{{- if .Values.producer.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "msa.fullname" . }}-producer
spec:
  schedule: "{{ .Values.producer.schedule }}"
  concurrencyPolicy: "{{ .Values.producer.concurrencyPolicy }}"
  successfulJobsHistoryLimit: {{ .Values.producer.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.producer.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      {{- if gt (int .Values.producer.parallelism) 0 }}
      parallelism: {{ int .Values.producer.parallelism }}
      {{- end }}
      {{- if gt (int .Values.producer.completions) 0 }}
      completions: {{ int .Values.producer.completions }}
      {{- end }}
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: producer
              image: '{{ printf "%s:%s" .Values.producer.image.repository (default "latest" .Values.producer.image.tag) }}'
              imagePullPolicy: {{ .Values.producer.image.pullPolicy }}
              args: ["producer"]
              volumeMounts:
               - name: hostpath-volume
                 mountPath: /data
              env:
                - name: BROKER_ADDR
                  value: "{{ .Values.producer.brokerAddr }}"
                - name: CSV_PATH
                  value: "{{ .Values.producer.csvPath }}"
                  
              {{- with .Values.producer.resources }}
              resources:
{{ toYaml . | nindent 16 }}
              {{- else }}
              resources: {}
              {{- end }}
          {{- if .Values.imagePullSecrets }}
          imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | nindent 12 }}
          {{- end }}
          volumes:
            - name: hostpath-volume
              hostPath:
                path: "{{ .Values.producer.dataHostPath }}"
                type: DirectoryOrCreate
{{- end }}
